# vim ft=yaml
# Multiple lines can be made a single "virtual line" because of the way that
# Travis munges each line before executing it to print out the exit status.
# It's okay for it to be on multiple physical lines, so long as you remember:
# - There can't be any leading "-"s - All newlines will be removed, so use
# ";"s
sudo: false  # To use travis container infrastructure
language: python
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
      # For numpy --pre wheels
      - libatlas-base-dev
env:
    global:
        # Maximal dependencies
        - DEPENDS="cython numpy scipy matplotlib"
python:
    - 2.6
    - 3.3
    - 3.4
    - 3.5
matrix:
  include:
    - python: 2.7
      env:
        - COVERAGE=1
    # To test minimum dependencies
    # Check these dependencies against regreg/info.py
    - python: 2.7
      env:
        - DEPENDS="cython==0.18 numpy==1.6.0 scipy==0.9.0"
    # Testing without matplotlib
    - python: 2.7
      env:
        - DEPENDS="cython numpy scipy"
    # test against pre-release builds
    - python: 2.7
      env:
        - EXTRA_PIP_FLAGS="--pre"
    # Documentation doctests
    - python: 2.7
      env:
        - DOC_DOC_TEST=1
    # Setup.py install
    - python: 2.7
      env:
        - INSTALL_TYPE=setup
    - python: 2.7
      env:
        # Sdist install should collect all dependencies
        - INSTALL_TYPE=sdist
        - DEPENDS=
    - python: 2.7
      env:
        # Wheel install should collect all dependencies
        - INSTALL_TYPE=wheel
        - DEPENDS=
    - python: 2.7
      env:
        - INSTALL_TYPE=requirements
        - DEPENDS=
before_install:
    - source travis-tools/utils.sh
    - travis_before_install
install:
    - travis_install $INSTALL_TYPE
# command to run tests, e.g. python setup.py test
script:
    - pip install nose
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    # No figure windows for mpl; quote to hide : from travis-ci yaml parsing
    - 'echo "backend : agg" > matplotlibrc'
    # Doctests only on platforms that have compatible fp output
    - if [ `uname` == "Darwin" ] ||
      [ "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]; then
      DOCTEST_ARGS="--with-doctest";
      fi
    - if [ "${COVERAGE}" == "1" ]; then
      cp ../.coveragerc .;
      COVER_ARGS="--with-coverage --cover-package regreg";
      fi
    - nosetests $DOCTEST_ARGS --verbose $COVER_ARGS regreg
after_success:
    - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
